controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

product_api_index:
  path: /api/products
  controller: 'App\Controller\ProductController::index'
  methods: ["GET"]

product_api_show:
  path: /api/products/{id}
  controller: 'App\Controller\ProductController::show'
  methods: ["GET"]

product_api_create:
  path: /api/products
  controller: 'App\Controller\ProductController::create'
  methods: ["POST"]

product_api_update:
  path: /api/products/{id}
  controller: 'App\Controller\ProductController::update'
  methods: ["PUT"]

product_api_delete:
  path: /api/products/{id}
  controller: 'App\Controller\ProductController::delete'
  methods: ["DELETE"]

api_login_check:
  path: /api/login_check

register_api:
  path: /api/register
  controller: 'App\Controller\RegistrationController::index'
  methods: ["POST"]